In [17]:
import tensorflow as tf
import numpy as np
import pandas as pd
#import tensorflow.contrib.eager as tfe
#tf.enable_eager_execution()

In [24]:
def trainDataLoad(local=False,market=True,news=True,sample=False):
    try:
        from kaggle.competitions import twosigmanews

        if(not local):
            env = twosigmanews.make_env()
        (market_df, news_df) = env.get_training_data()

        print('Data fetched from kaggle with {} rows of market data and {} rows of news data'.format(market_df.shape, news_df.shape))
    except:
        filename=['marketdata_sample.csv','news_sample.csv']
        if(not sample):
            filename=['market_train.csv','news_train.csv']
        print('failed to load data from kaggle, loading data from local directory.')
        if(market):
            market_df=pd.read_csv('./sampleData/'+filename[0])
        if(news):
            news_df=pd.read_csv('./sampleData/'+filename[1])
        print('Train data loaded!')
    if(market & (not news)):
        return market_df
    if(news & (not market)):
        return news_df
    return (market_df,news_df)

# Embeddings

### Example for embedding lookups

In [11]:
# 定义一个未知变量input_ids用于存储索引
input_ids = tf.placeholder(dtype=tf.int32, shape=[None])

# 定义一个已知变量embedding，是一个5*5的对角矩阵
# embedding = tf.Variable(np.identity(5, dtype=np.int32))

# 或者随机一个矩阵
embedding = a = np.asarray([[0.1, 0.2, 0.3], [1.1, 1.2, 1.3], [2.1, 2.2, 2.3], [3.1, 3.2, 3.3], [4.1, 4.2, 4.3]])

# 根据input_ids中的id，查找embedding中对应的元素
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

print(sess.run(input_embedding, feed_dict={input_ids: [1, 2, 3, 0, 3, 2, 1]}))



[[1.1 1.2 1.3]
 [2.1 2.2 2.3]
 [3.1 3.2 3.3]
 [0.1 0.2 0.3]
 [3.1 3.2 3.3]
 [2.1 2.2 2.3]
 [1.1 1.2 1.3]]


In [ ]:
def createEmbeddings(itemIds,embeddings,init,name='embeddings'):
    embeddings = tf.Variable(embedding_init,name=name,dtype=tf.float64)
    embedded_ids = tf.nn.embedding_lookup(embeddings, itemIds)
    return embedded_ids

In [25]:
news_train_df=trainDataLoad(news=False,sample=True)

failed to load data from kaggle, loading data from local directory.
Train data loaded!


In [27]:
news_train_df.assetCode.unique()

array(['A.N', 'AAI.N', 'AAP.N', 'AAPL.O', 'ABB.N', 'ABC.N', 'ABD.N',
       'ABM.N', 'ABT.N', 'ABV.N', 'ABY.N', 'ACF.N', 'ACH.N', 'ACL.N',
       'ACS.N', 'ACTS.O', 'ACXM.O', 'AD.N', 'ADBE.O', 'ADCT.O', 'ADI.N',
       'ADM.N', 'ADP.N', 'ADS.N', 'ADSK.O', 'ADTN.O', 'AEA.N', 'AEE.N',
       'AEG.N', 'AEIS.O', 'AEL.N', 'AEOS.O', 'AEP.N', 'AER.N', 'AES.N',
       'AET.N', 'AF.N', 'AFFX.O', 'AFG.N', 'AFL.N', 'AFR.N', 'AG.N',
       'AGE.N', 'AGN.N', 'AGU.N', 'AH.N', 'AHG.N', 'AHL.N', 'AHS.N',
       'AHT.N', 'AIN.N', 'AINV.O', 'AIR.N', 'AIT.N', 'AIV.N', 'AIZ.N',
       'AJG.N', 'AKAM.O', 'AKR.N', 'AKS.N', 'ALB.N', 'ALD.N', 'ALGN.O',
       'ALK.N', 'ALL.N', 'ALNY.O', 'ALO.N', 'ALTR.O', 'ALU.N', 'ALV.N',
       'ALXN.O', 'AMAT.O', 'AMD.N', 'AME.N', 'AMED.O', 'AMG.N', 'AMGN.O',
       'AMKR.O', 'AMLN.O', 'AMMD.O', 'AMP.N', 'AMT.N', 'AMTD.O', 'AMX.N',
       'AMZN.O', 'AN.N', 'ANDE.O', 'ANDW.O', 'ANF.N', 'ANR.N', 'AOC.N',
       'AOS.N', 'APA.N', 'APC.N', 'APD.N', 'APH.N', 'APKT.O', 'APOL.O',